import{S as y,a as h,i as p}from"./assets/vendor-89feecc5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))d(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function t(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerpolicy&&(a.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?a.credentials="include":r.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function d(r){if(r.ep)return;r.ep=!0;const a=t(r);fetch(r.href,a)}})();const u=document.querySelector(".form"),i=document.querySelector(".gallery");document.querySelector(".loader");const m=document.querySelector(".load_more_btn"),b=document.querySelector(".loader-container"),L="https://pixabay.com/api/?",v="41732338-ca5909782120305119b6393dc",s={key:v,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:40},S=new y(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,enableKeyboard:!0,docClose:!0}),l=e=>{m.style.display=e?"flex":"none"},n=e=>{b.style.display=e?"flex":"none"},x=e=>e.reduce((o,t)=>o+`
    <li class="gallery-item">
      <a href="${t.largeImageURL}"> 
        <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
      </a>
      <div class="gallery-text-box">
        <p>Likes: <span class="text-value">${t.likes}</span></p>
        <p>Views: <span class="text-value">${t.views}</span></p>
        <p>Comments: <span class="text-value">${t.comments}</span></p>
        <p>Downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
    </li>
    `,""),f=async()=>{var e;try{const o=await h.get(L,{params:{...s,page:s.page,q:s.q}});if(o.data.hits.length===0)p.error({position:"bottomCenter",messageColor:"#FFFFFF",backgroundColor:"#EF4040",titleSize:"8px",closeOnEscape:!0,message:"Sorry, there are no images matching your search query. Please try again!"});else{const t=(e=i.querySelector(".gallery-item"))==null?void 0:e.getBoundingClientRect().height;i.innerHTML+=x(o.data.hits),S.refresh(),s.page*s.per_page>=o.data.totalHits?(l(!1),p.info({position:"bottomCenter",messageColor:"#FFFFFF",backgroundColor:"#3e4f65",titleSize:"8px",closeOnEscape:!0,message:"We're sorry, but you've reached the end of search results."})):l(!0),window.scrollBy({top:t*2,behavior:"smooth"})}}catch(o){console.error(o.message)}finally{n(!1)}},F=()=>{s.page+=1,n(!0),f()},g=async e=>{e.preventDefault(),n(!0),l(!1);const o=e.target.elements.search,t=encodeURIComponent(o.value.trim());if(t===""){console.error("Please enter a valid search query."),n(!1);return}s.q=t,s.page=1,i.innerHTML="",await f(),n(!1),l(!0),u.dataset.searchTerm=t};u.addEventListener("submit",g);m.addEventListener("click",F);document.addEventListener("DOMContentLoaded",()=>{const e=u.dataset.searchTerm;e&&g({target:{elements:{search:{value:e}}}})});
//# sourceMappingURL=commonHelpers.js.map
