import{S as h,i as u,a as b}from"./assets/vendor-89feecc5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const F="41732338-ca5909782120305119b6393dc";let n="";const S=document.querySelector(".form"),i=document.querySelector(".gallery"),L=document.querySelector(".loader"),y=document.querySelector(".load_more_btn"),v=document.querySelector(".loader-container"),p=document.querySelector(".preloader"),w=new h(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,enableKeyboard:!0,docClose:!0}),x=e=>{L.style.display=e?"block":"none"},d=e=>{const s=e&&i.children.length>=40;y.style.display=s?"flex":"none"},l=e=>{v.style.display=e?"flex":"none"},m=e=>{if(p.style.display=e?"block":"none",e){const o=document.querySelector('.form input[name="search"]').getBoundingClientRect();p.style.top=`${o.bottom+32}px`}},q=e=>e.reduce((s,o)=>s+`
    <li class="gallery-item">
      <a href="${o.largeImageURL}"> 
        <img class="gallery-img" src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="gallery-text-box">
        <p>Likes: <span class="text-value">${o.likes}</span></p>
        <p>Views: <span class="text-value">${o.views}</span></p>
        <p>Comments: <span class="text-value">${o.comments}</span></p>
        <p>Downloads: <span class="text-value">${o.downloads}</span></p>
      </div>
    </li>
    `,""),g=async({query:e,page:s,perPage:o})=>{var t;const c="https://pixabay.com/api/?";try{m(!0);const r=await b.get(c,{params:{key:F,q:e,page:s,per_page:o,image_type:"photo",orientation:"horizontal",safesearch:!0}});if(r.data.hits.length===0)s===1&&u.error({position:"bottomRight",messageColor:"#FFFFFF",backgroundColor:"#EF4040",titleSize:"8px",closeOnEscape:!0,message:"Sorry, there are no images matching your search query. Please try again!"});else{const a=(t=i.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height;i.insertAdjacentHTML("beforeend",q(r.data.hits)),w.refresh(),s*o>=r.data.totalHits?(d(!1),u.info({position:"bottomRight",messageColor:"#FFFFFF",backgroundColor:"#3e4f65",titleSize:"8px",closeOnEscape:!0,message:"We're sorry, but you've reached the end of search results."})):d(!0),window.scrollBy({top:a*2,behavior:"smooth"})}}catch{u.error({position:"bottomRight",messageColor:"#FFFFFF",backgroundColor:"#EF4040",titleSize:"8px",closeOnEscape:!0,message:"An error occurred while fetching images. Please try again."})}finally{m(!1),l(!1)}},C=async()=>{const e={query:n,page:Math.ceil(i.children.length/40)+1,perPage:40};l(!0),await g(e)},f=async e=>{e.preventDefault(),l(!0),d(!1);const s=e.target.elements.search;if(n=encodeURIComponent(s.value.trim()),n===""){u.error({position:"bottomRight",messageColor:"#FFFFFF",backgroundColor:"#EF4040",titleSize:"8px",closeOnEscape:!0,message:"Please enter a valid search query."}),l(!1);return}const o={query:n,page:1,perPage:40};i.innerHTML="",x(!0),await g(o),l(!1),d(!0)};S.addEventListener("submit",f);y.addEventListener("click",C);document.addEventListener("DOMContentLoaded",()=>{const e=n;e&&f({target:{elements:{search:{value:e}}}})});
//# sourceMappingURL=commonHelpers.js.map
