import{S as y,i as u,a as h}from"./assets/vendor-89feecc5.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();let n="";const F=document.querySelector(".form"),i=document.querySelector(".gallery"),b=document.querySelector(".loader"),p=document.querySelector(".load_more_btn"),L=document.querySelector(".loader-container"),S=new y(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,enableKeyboard:!0,docClose:!0}),v=e=>{b.style.display=e?"block":"none"},d=e=>{const s=e&&i.children.length>=40;p.style.display=s?"flex":"none"},l=e=>{L.style.display=e?"flex":"none"},w=e=>e.reduce((s,o)=>s+`
    <li class="gallery-item">
      <a href="${o.largeImageURL}"> 
        <img class="gallery-img" src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="gallery-text-box">
        <p>Likes: <span class="text-value">${o.likes}</span></p>
        <p>Views: <span class="text-value">${o.views}</span></p>
        <p>Comments: <span class="text-value">${o.comments}</span></p>
        <p>Downloads: <span class="text-value">${o.downloads}</span></p>
      </div>
    </li>
    `,""),m=async({query:e,page:s,perPage:o})=>{var r;const c="https://pixabay.com/api/?",t="41732338-ca5909782120305119b6393dc";try{v(!0);const a=await h.get(c,{params:{key:t,q:e,page:s,per_page:o}});if(a.data.hits.length===0)s===1&&u.error({position:"bottomRight",messageColor:"#FFFFFF",backgroundColor:"#EF4040",titleSize:"8px",closeOnEscape:!0,message:"Sorry, there are no images matching your search query. Please try again!"});else{const f=(r=i.querySelector(".gallery-item"))==null?void 0:r.getBoundingClientRect().height;i.insertAdjacentHTML("beforeend",w(a.data.hits)),S.refresh(),s*o>=a.data.totalHits?(d(!1),u.info({position:"bottomRight",messageColor:"#FFFFFF",backgroundColor:"#3e4f65",titleSize:"8px",closeOnEscape:!0,message:"We're sorry, but you've reached the end of search results."})):d(!0),window.scrollBy({top:f*2,behavior:"smooth"})}}catch{u.error({position:"bottomRight",messageColor:"#FFFFFF",backgroundColor:"#EF4040",titleSize:"8px",closeOnEscape:!0,message:"An error occurred while fetching images. Please try again."})}finally{l(!1)}},x=async()=>{const e={query:n,page:Math.ceil(i.children.length/40)+1,perPage:40};l(!0),await m(e)},g=async e=>{e.preventDefault(),l(!0),d(!1);const s=e.target.elements.search;if(n=encodeURIComponent(s.value.trim()),n===""){u.error({position:"bottomRight",messageColor:"#FFFFFF",backgroundColor:"#EF4040",titleSize:"8px",closeOnEscape:!0,message:"Please enter a valid search query."}),l(!1);return}const o={query:n,page:1,perPage:40};i.innerHTML="",await m(o),l(!1),d(!0)};F.addEventListener("submit",g);p.addEventListener("click",x);document.addEventListener("DOMContentLoaded",()=>{const e=n;e&&g({target:{elements:{search:{value:e}}}})});
//# sourceMappingURL=commonHelpers.js.map
